DEF NUM_CUSTOM_BALLS EQU 16
DEF CUSTOM_BALL_DATA_SIZE EQU 3 ; 3 bytes per custom ball

; Ball Data format IDs (which nybble each piece of data is stored at in wram struct)
; Low nybble, high nybble
	const_def
	const BALL_CUSTOM_FORMAT_COLOR
	const BALL_CUSTOM_FORMAT_TILE
	const BALL_CUSTOM_FORMAT_SFX
	const BALL_CUSTOM_FORMAT_THROW
	const BALL_CUSTOM_FORMAT_FLAGS
	const BALL_CUSTOM_FORMAT_POOF

; Ball Tile IDs
	const_def
	const BALL_TILE_SPHERE
	const BALL_TILE_SPARKLE
	const BALL_TILE_ROCK
	const BALL_TILE_DROPLET
	const BALL_TILE_LEAF
	const BALL_TILE_FIRE
	const BALL_TILE_CRYSTAL
	const BALL_TILE_SHINE
	const BALL_TILE_SWORD
	const BALL_TILE_SKULL
	const BALL_TILE_BOLT
	const BALL_TILE_TRI
	const BALL_TILE_HEART
	const BALL_TILE_EYE
	const BALL_TILE_GHOST
	const BALL_TILE_CONE
	
; Ball Colors
	const_def
	const BALL_COLOR_RED
	const BALL_COLOR_YELLOW
	const BALL_COLOR_PALE
	const BALL_COLOR_GREEN
	const BALL_COLOR_CYAN
	const BALL_COLOR_BLUE
	const BALL_COLOR_INDIGO
	const BALL_COLOR_PURPLE
	const BALL_COLOR_PINK
	const BALL_COLOR_GRAY
	const BALL_COLOR_BLACK
	const BALL_COLOR_WHITE
	const BALL_COLOR_REDYELLOW
	const BALL_COLOR_GREENYELLOW
	const BALL_COLOR_CRIMSON
	const BALL_COLOR_MULTI

; Ball Throw animations
	const_def
	const BALL_THROW_NONE
	const BALL_THROW_APPEAR
	const BALL_THROW_FLASH
	const BALL_THROW_SHAKE
	const BALL_THROW_VIBRATE
	const BALL_THROW_THROW
	const BALL_THROW_DROP
	const BALL_THROW_BOUNCE
	const BALL_THROW_ROLL
	const BALL_THROW_ZIGZAG
	const BALL_THROW_FAKEOUT
	const BALL_THROW_EMOTION
	const BALL_THROW_THE_MERGING
	const BALL_THROW_SLICE
	const BALL_THROW_ANGELIC
	const BALL_THROW_RANDOM

; Ball Poof Sound Effects
	const_def
	const BALL_SFX_ORIGINAL
	const BALL_SFX_WIND
	const BALL_SFX_SHWING
	const BALL_SFX_WHOOSH
	const BALL_SFX_SMASH
	const BALL_SFX_CUTE
	const BALL_SFX_SQUIRT
	const BALL_SFX_POWER_UP
	const BALL_SFX_PSY
	const BALL_SFX_EVIL
	const BALL_SFX_ICY
	const BALL_SFX_MACHINE
	const BALL_SFX_FLOOD
	const BALL_SFX_EXPLODE
	const BALL_SFX_THUNDER
	const BALL_SFX_SPARKLE

; Ball Poof animations
	const_def
	const BALL_POOF_ORIGINAL
	const BALL_POOF_SPREAD
	const BALL_POOF_CIRCLE_AROUND
	const BALL_POOF_CIRCLE_SPREAD
	const BALL_POOF_SPIRAL
	const BALL_POOF_GRAVITY
	const BALL_POOF_CRISSCROSS
	const BALL_POOF_SCAN
	const BALL_POOF_WINDMILL
	const BALL_POOF_STRIKE
	const BALL_POOF_SPECKLE
	const BALL_POOF_CONFETTI
	const BALL_POOF_HELIX
	const BALL_POOF_TORNADO
	const BALL_POOF_EXPLOSION
	const BALL_POOF_RANDOM

; PokeBall Data IDs
	const_def
	const BALL_DATA_POKE
	const BALL_DATA_GREAT
	const BALL_DATA_ULTRA
	const BALL_DATA_SAFARI
	const BALL_DATA_HYPER
	const BALL_DATA_MASTER
	DEF FIRST_CUSTOM_BALL_DATA_CONST EQU const_value
	const BALL_DATA_CUSTOM1
	const BALL_DATA_CUSTOM2
	const BALL_DATA_CUSTOM3
	const BALL_DATA_CUSTOM4
	const BALL_DATA_CUSTOM5
	const BALL_DATA_CUSTOM6
	const BALL_DATA_CUSTOM7
	const BALL_DATA_CUSTOM8
	const BALL_DATA_CUSTOM9
	const BALL_DATA_CUSTOM10
	const BALL_DATA_CUSTOM11
	const BALL_DATA_CUSTOM12
	const BALL_DATA_CUSTOM13
	const BALL_DATA_CUSTOM14
	const BALL_DATA_CUSTOM15
	const BALL_DATA_CUSTOM16
	const PAST_LAST_CUSTOM_BALL_DATA_CONST

; Custom Pokeball IDs
	const_def
	const BALL_ID_FOREST
	const BALL_ID_DRENCH
	const BALL_ID_BLAZE
	const BALL_ID_CUTE
	const BALL_ID_BOLT
	const BALL_ID_TRI
	const BALL_ID_BOULDER
	const BALL_ID_SUBZERO
	const BALL_ID_MIND
	const BALL_ID_TORNADO
	const BALL_ID_VENOM
	const BALL_ID_SPOOKY
	const BALL_ID_CLEAVE
	const BALL_ID_ANGEL
	const BALL_ID_BOMB
	const BALL_ID_PRISM
	