DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "JACK"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "JOHN"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "BLUE"
DEF PLAYERNAME2 EQUS "GARY"
DEF PLAYERNAME3 EQUS "JOHN"

DEF RIVALNAME1 EQUS "RED"
DEF RIVALNAME2 EQUS "ASH"
DEF RIVALNAME3 EQUS "JACK"
ENDC

IF DEF(_GREEN) ; PureRGBnote: GREENBUILD: default names specific to pokemon green
DEF PLAYERNAME1 EQUS "GREEN"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "MIKE"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "GABE"
ENDC
