name: Review
description: Write a review of the game.
title: "[Review]: Summarize your review here"
labels: ["review"]
body:
  - type: dropdown
    id: played
    attributes:
      label: Did you finish playing the game before leaving a review?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: review
    attributes:
      label: Review Content
      description: Write your review here.
      placeholder: I was whelmed by PureRGB.
    validations:
      required: true
